# Generated by Django 3.2.7 on 2021-10-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('IATA_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('passportSeries', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('passportNum', models.CharField(max_length=6)),
                ('FIO', models.CharField(max_length=100)),
                ('Miles', models.FloatField()),
            ],
            options={
                'unique_together': {('passportSeries', 'passportNum')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('Flight_ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('DateFrom', models.DateTimeField()),
                ('DateTo', models.DateTimeField()),
                ('CountOfTickets', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickets.aircompany')),
                ('airFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airFrom', to='tickets.airports')),
                ('airTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airTo', to='tickets.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='tickets.country')),
            ],
        ),
        migrations.AddField(
            model_name='airports',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.town'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Seq', models.IntegerField(primary_key=True, serialize=False)),
                ('Cost', models.IntegerField()),
                ('Seat', models.CharField(max_length=5)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.customers')),
                ('FlightOfTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='tickets.flight')),
            ],
            options={
                'unique_together': {('Seq', 'FlightOfTicket')},
            },
        ),
    ]
