# Generated by Django 3.2.7 on 2021-10-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='FIO',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_buy', to='tickets.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Passenger',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger', verbose_name='Пассажир'),
        ),
    ]
