# Generated by Django 3.2.7 on 2021-10-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20211012_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_buy', to='tickets.customer', verbose_name='Покупатель'),
        ),
    ]
