# Generated by Django 3.2.7 on 2021-10-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20211005_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('passportSeries', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('passportNum', models.CharField(max_length=6)),
                ('FIO', models.CharField(max_length=100)),
                ('Miles', models.FloatField()),
            ],
            options={
                'unique_together': {('passportSeries', 'passportNum')},
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Seq', models.IntegerField(primary_key=True, serialize=False)),
                ('Cost', models.IntegerField(verbose_name='Цена')),
                ('Seat', models.CharField(max_length=5)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.customers')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='FlightOfTicket',
        ),
        migrations.AlterModelOptions(
            name='aircompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='Miles',
        ),
        migrations.AlterField(
            model_name='flight',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickets.aircompany'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DateFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DateTo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_ID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airFrom', to='tickets.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airTo', to='tickets.airport'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='tickets',
            name='FlightOfTicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='tickets.flight'),
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('Seq', 'FlightOfTicket')},
        ),
    ]
