# Generated by Django 3.2.7 on 2021-10-09 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_auto_20211006_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('passportSeries', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('passportNum', models.CharField(max_length=6)),
                ('FIO', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'unique_together': {('passportSeries', 'passportNum')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Seq', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Номер')),
                ('Cost', models.IntegerField(verbose_name='Цена')),
                ('Seat', models.CharField(max_length=5, verbose_name='Место')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='tickets.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='FlightOfTicket',
        ),
        migrations.AlterModelOptions(
            name='aircompany',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickets.aircompany', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DateFrom',
            field=models.DateTimeField(verbose_name='Время вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DateTo',
            field=models.DateTimeField(verbose_name='Время прилета (прибл.)'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_ID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Miles',
            field=models.FloatField(default=0, verbose_name='Количетсво миль'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airFrom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airFrom', to='tickets.airport', verbose_name='Вылет из'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airTo', to='tickets.airport', verbose_name='Прилет в'),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='FlightOfTicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flight'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('Seq', 'FlightOfTicket')},
        ),
    ]
