# Generated by Django 3.2.7 on 2021-10-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20211009_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircompany',
            options={'verbose_name': 'Авиакомпания', 'verbose_name_plural': 'Авиакомпании'},
        ),
    ]
