# Generated by Django 3.2.7 on 2021-10-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20211009_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pass_tickets', to='tickets.passenger', verbose_name='Пассажир'),
        ),
    ]
