# Generated by Django 3.2.7 on 2021-10-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20211009_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buy_tickets', to='tickets.customer', verbose_name='Покупатель'),
        ),
    ]
