# Generated by Django 3.2.7 on 2021-10-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20211009_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Customer',
            new_name='Customer_buy',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Passenger',
            new_name='Passenger_own',
        ),
    ]
