# Generated by Django 3.2.7 on 2021-10-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20211009_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Customer_buy',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Passenger_own',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger', verbose_name='Пассажир'),
        ),
    ]
